version: '3.8'

networks:
  laravel:

services:
  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - ${DOCKER_CONTAINER_IP}:8081:80
    depends_on:
      - php
      - mysql
      - composer
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${APP_TIMEZONE}
    ports:
      - ${DOCKER_CONTAINER_IP}:3307:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel
  php:
    container_name: php
    build: ./docker/php
    ports:
      - ${DOCKER_CONTAINER_IP}:9000:9000
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - laravel
    ports:
      - ${DOCKER_CONTAINER_IP}:6380:6379
  composer:
    container_name: composer
    image: composer:2
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  cron:
    build: ./docker/cron
    container_name: cron
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    depends_on:
      - nginx
